import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { Oswald } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";


// const oswald = Oswald({
//   subsets: ["latin"],
//   variable: "--font-oswald",
// });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className='bg-black text-white'
    >
      
      <body  className=''>
        <NavBar></NavBar>
        {children}</body>
    </html>
  );
}
